### PR TITLE
Depend on released interfaces pkgs by default

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Introduce a `.repos` which can be used for full-source builds.

The default `.repos` then no longer includes those packages.

We can't merge it until Melodic and Noetic have seen a sync (Kinetic has already been synced).

Status can be tracked here:

 - [status_page/ros_melodic_default.html?q=abb_](http://repositories.ros.org/status_page/ros_melodic_default.html?q=abb_)
 - [status_page/ros_noetic_default.html?q=abb_](http://repositories.ros.org/status_page/ros_noetic_default.html?q=abb_)

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
> We can't merge it until Melodic and Noetic have seen a sync

This also means CI will fail for the non-`testing` variants (as the `testing` builds pull packages from the staging repositories).

**Review by jontje — APPROVED** [review]
Looks good to me 👍

**Comment by gavanderhoorn** [comment]
We're still waiting for Melodic and Noetic syncs.

**Comment by gavanderhoorn** [comment]
Seems Melodic has seen a sync, so CI should now succeed there.

I've triggered the jobs.

**Comment by gavanderhoorn** [comment]
As both Melodic and Noetic have seen a sync since I've released the msg packages, this build now succeeds.

And as @jontje already accepted the PR, I'm going to merge it.

**Pull request merged**
